const samplelistings = [
    {
        title: "sandy soil",
        image: "https://www.boughton.co.uk/wp-content/uploads/sites/14/2019/07/Sandy-Soil-1.jpg",
        monthlycycle: [
            { "month": "January", "crop": "Peas (Legumes)", "action": "Peas are a winter crop that thrives in cooler temperatures and sandy soil. They help fix nitrogen in the soil, preparing it for the next crop. Sow peas in January and let them grow until February." },
            { "month": "February", "crop": "Peas (Legumes)", "action": "Peas are a winter crop that thrives in cooler temperatures and sandy soil. They help fix nitrogen in the soil, preparing it for the next crop. Sow peas in January and let them grow until February." },
            { "month": "March ", "crop": " Sweet Corn (Grains)", "action": "After harvesting peas, plant sweet corn in March. Corn benefits from the nitrogen fixed by peas and grows well in sandy soil, which provides the drainage it needs. Harvest typically occurs by late April or early May." },
            { "month": "April", "crop": " Sweet Corn (Grains)", "action": "After harvesting peas, plant sweet corn in March. Corn benefits from the nitrogen fixed by peas and grows well in sandy soil, which provides the drainage it needs. Harvest typically occurs by late April or early May." },
            { "month": "May", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Following the corn harvest, plant cucumbers or zucchini in May. These crops are ideal for the warm weather and well-drained sandy soil. They grow quickly and help cover the soil, reducing the risk of erosion." },
            { "month": "June", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Following the corn harvest, plant cucumbers or zucchini in May. These crops are ideal for the warm weather and well-drained sandy soil. They grow quickly and help cover the soil, reducing the risk of erosion." },
            { "month": "July", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In July, switch to planting spinach or lettuce. These leafy greens can handle the slightly cooler temperatures as summer progresses and grow well in sandy soil. They also utilize the nutrients left by the previous crops." },
            { "month": "August", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In July, switch to planting spinach or lettuce. These leafy greens can handle the slightly cooler temperatures as summer progresses and grow well in sandy soil. They also utilize the nutrients left by the previous crops." },
            { "month": "September ", "crop": "Carrots or Radishes (Root Vegetables)", "action": "As fall approaches, plant carrots or radishes in September. These root vegetables thrive in sandy soil, which allows for easy root development. They should be ready for harvest by October or early November." },
            { "month": "October", "crop": "Carrots or Radishes (Root Vegetables)", "action": "As fall approaches, plant carrots or radishes in September. These root vegetables thrive in sandy soil, which allows for easy root development. They should be ready for harvest by October or early November." },
            { "month": "November", "crop": "Clover or Rye (Green Manure)", "action": "After harvesting root vegetables, plant a green manure crop like clover or rye in November. These crops will help restore soil fertility, add organic matter, and protect the soil from erosion. Allow them to grow through November." },
            { "month": "December", "crop": "December: Peas (Legumes)", "action": "Return to peas in December to begin the cycle anew. Peas are well-suited for planting in cooler temperatures and will start the next cycle by fixing nitrogen in the soil." },
        ],
        summarybycroptype: [
            { "month": "January", "summry": "Legumes (Peas):" },
            { "month": "February", "summry": "Legumes (Peas):" },
            { "month": "March", "summry": "Grains (Sweet Corn)" },
            { "month": "April", "summry": "Grains (Sweet Corn)" },
            { "month": "May", "summry": "Cucurbits (Cucumbers/Zucchini)" },
            { "month": "June", "summry": "Cucurbits (Cucumbers/Zucchini)" },
            { "month": "July", "summry": "Leafy Greens (Spinach/Lettuce)" },
            { "month": "August", "summry": "Leafy Greens (Spinach/Lettuce)" },
            { "month": "September", "summry": "Root Vegetables (Carrots/Radishes)" },
            { "month": "October", "summry": "Root Vegetables (Carrots/Radishes)" },
            { "month": "December", "summry": "Legumes (Peas):" },
        ],
        additionaltips: "Legumes (Peas): January-February, December. Grains (Sweet Corn): March-April. Cucurbits (Cucumbers/Zucchini): May-June. Leafy Greens (Spinach/Lettuce): July-August. Root Vegetables (Carrots/Radishes): September-October. Green Manure (Clover/Rye): November."
    },
    {
        "title": "Clay Soil",
        "image": "https://www.boughton.co.uk/wp-content/uploads/sites/14/2019/07/Clay-Soil-1.jpg",
        "monthlycycle": [
            { "month": "January", "crop": "Peas (Legumes)", "action": "Peas are a good choice for winter planting in clay soil, as they improve soil structure and fix nitrogen. Sow in January and allow them to grow through February. They help break up the clay and add fertility." },
            { "month": "February", "crop": "Peas (Legumes)", "action": "Peas are a good choice for winter planting in clay soil, as they improve soil structure and fix nitrogen. Sow in January and allow them to grow through February. They help break up the clay and add fertility." },
            { "month": "March", "crop": "Brassicas", "action": "Plant brassicas (cabbage, broccoli, or cauliflower) in early spring. They benefit from the nutrients left by peas and can handle the cooler temperatures. They grow well in clay soil, which retains moisture." },
            { "month": "April", "crop": "Brassicas", "action": "Plant brassicas (cabbage, broccoli, or cauliflower) in early spring. They benefit from the nutrients left by peas and can handle the cooler temperatures. They grow well in clay soil, which retains moisture." },
            { "month": "May", "crop": "Root Vegetables", "action": "Plant root vegetables like carrots, beets, or radishes in May. Clay soil’s nutrient-rich nature is ideal for these crops, though you may need to amend the soil with organic matter to improve drainage and reduce compaction. Harvest by late June." },
            { "month": "June", "crop": "Root Vegetables", "action": "Plant root vegetables like carrots, beets, or radishes in May. Clay soil’s nutrient-rich nature is ideal for these crops, though you may need to amend the soil with organic matter to improve drainage and reduce compaction. Harvest by late June." },
            { "month": "July", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Plant cucumbers or zucchini in July. These summer crops thrive in the warm weather and benefit from the retained moisture in clay soil. They also help cover the soil, preventing erosion." },
            { "month": "August", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Plant cucumbers or zucchini in July. These summer crops thrive in the warm weather and benefit from the retained moisture in clay soil. They also help cover the soil, preventing erosion." },
            { "month": "September", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In early fall, plant spinach or lettuce. These leafy greens will grow well in the cooler temperatures and utilize the nutrients from previous crops. Clay soil's moisture retention is beneficial during this period." },
            { "month": "October", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In early fall, plant spinach or lettuce. These leafy greens will grow well in the cooler temperatures and utilize the nutrients from previous crops. Clay soil's moisture retention is beneficial during this period." },
            { "month": "November", "crop": "Green Manure", "action": "Plant green manure crops such as clover or vetch. These crops will help improve soil structure, add organic matter, and prevent erosion during the winter months." },
            { "month": "December", "crop": "Green Manure", "action": "Plant green manure crops such as clover or vetch. These crops will help improve soil structure, add organic matter, and prevent erosion during the winter months." }
        ],
        "summarybycroptype": [
            { "month": "January", "summary": "Legumes (Peas)" },
            { "month": "February", "summary": "Legumes (Peas)" },
            { "month": "March", "summary": "Brassicas (Cabbage/Broccoli/Cauliflower)" },
            { "month": "April", "summary": "Brassicas (Cabbage/Broccoli/Cauliflower)" },
            { "month": "May", "summary": "Root Vegetables (Carrots/Beets/Radishes)" },
            { "month": "June", "summary": "Root Vegetables (Carrots/Beets/Radishes)" },
            { "month": "July", "summary": "Cucurbits (Cucumbers/Zucchini)" },
            { "month": "August", "summary": "Cucurbits (Cucumbers/Zucchini)" },
            { "month": "September", "summary": "Leafy Greens (Spinach/Lettuce)" },
            { "month": "October", "summary": "Leafy Greens (Spinach/Lettuce)" },
            { "month": "November", "summary": "Green Manure (Clover/Vetch)" },
            { "month": "December", "summary": "Green Manure (Clover/Vetch)" }
        ],
        "additionaltips": "Legumes (Peas): January-February. Brassicas (Cabbage/Broccoli/Cauliflower): March-April. Root Vegetables (Carrots/Beets/Radishes): May-June. Cucurbits (Cucumbers/Zucchini): July-August. Leafy Greens (Spinach/Lettuce): September-October. Green Manure (Clover/Vetch): November-December."
    },
    {
        "title": "Silty Soil",
        "image": "https://www.boughton.co.uk/wp-content/uploads/sites/14/2019/07/Silt-Soil.jpg",
        "monthlycycle": [
            {"month": "January", "crop": "Peas (Legumes)", "action": "Peas can be grown in silty soil during winter months. They help fix nitrogen and improve soil fertility. Plant in January and let them grow until February."},
            {"month": "February", "crop": "Peas (Legumes)", "action": "Peas can be grown in silty soil during winter months. They help fix nitrogen and improve soil fertility. Plant in January and let them grow until February."},
            {"month": "March", "crop": "Brassicas", "action": "Plant brassicas like cabbage or cauliflower in March. Silty soil’s moisture retention is beneficial for these crops. They grow well in cooler temperatures and benefit from the nutrients in the soil."},
            {"month": "April", "crop": "Brassicas", "action": "Plant brassicas like cabbage or cauliflower in March. Silty soil’s moisture retention is beneficial for these crops. They grow well in cooler temperatures and benefit from the nutrients in the soil."},
            {"month": "May", "crop": "Root Vegetables", "action": "Plant root vegetables such as carrots or beets in May. Silty soil provides good moisture and nutrients for root development. Harvest by late June."},
            {"month": "June", "crop": "Root Vegetables", "action": "Plant root vegetables such as carrots or beets in May. Silty soil provides good moisture and nutrients for root development. Harvest by late June."},
            {"month": "July", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Cucumbers or zucchini can be planted in July. Silty soil’s moisture retention is beneficial for these crops during the hot summer months."},
            {"month": "August", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Cucumbers or zucchini can be planted in July. Silty soil’s moisture retention is beneficial for these crops during the hot summer months."},
            {"month": "September", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In early fall, plant spinach or lettuce. These leafy greens thrive in the cooler temperatures and benefit from the retained moisture in silty soil."},
            {"month": "October", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In early fall, plant spinach or lettuce. These leafy greens thrive in the cooler temperatures and benefit from the retained moisture in silty soil."},
            {"month": "November", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These crops help improve soil fertility and structure and prevent erosion during the winter months."},
            {"month": "December", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These crops help improve soil fertility and structure and prevent erosion during the winter months."}
        ],
        "summarybycroptype": [
            {"month": "January", "summary": "Legumes (Peas)"},
            {"month": "February", "summary": "Legumes (Peas)"},
            {"month": "March", "summary": "Brassicas (Cabbage/Cauliflower)"},
            {"month": "April", "summary": "Brassicas (Cabbage/Cauliflower)"},
            {"month": "May", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "June", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "July", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "August", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "September", "summary": "Leafy Greens (Spinach/Lettuce)"},
            {"month": "October", "summary": "Leafy Greens (Spinach/Lettuce)"},
            {"month": "November", "summary": "Green Manure (Clover/Vetch)"},
            {"month": "December", "summary": "Green Manure (Clover/Vetch)"}
        ],
        "additionaltips": "Legumes (Peas): January-February. Brassicas (Cabbage/Cauliflower): March-April. Root Vegetables (Carrots/Beets): May-June. Cucurbits (Cucumbers/Zucchini): July-August. Leafy Greens (Spinach/Lettuce): September-October. Green Manure (Clover/Vetch): November-December."
    },
    {
        "title": "Loamy Soil",
        "image": "https://www.boughton.co.uk/wp-content/uploads/sites/14/2019/07/Loam-Soil.jpg",
        "monthlycycle": [
            {"month": "January", "crop": "Peas (Legumes)", "action": "Peas are well-suited for loamy soil. They can be planted in January, and their ability to fix nitrogen improves soil fertility. They should be grown until February."},
            {"month": "February", "crop": "Peas (Legumes)", "action": "Peas are well-suited for loamy soil. They can be planted in January, and their ability to fix nitrogen improves soil fertility. They should be grown until February."},
            {"month": "March", "crop": "Brassicas", "action": "Plant brassicas like cabbage or cauliflower in March. Loamy soil's balanced texture provides ideal conditions for these crops to grow and develop."},
            {"month": "April", "crop": "Brassicas", "action": "Plant brassicas like cabbage or cauliflower in March. Loamy soil's balanced texture provides ideal conditions for these crops to grow and develop."},
            {"month": "May", "crop": "Root Vegetables", "action": "In May, plant root vegetables such as carrots or beets. Loamy soil's good drainage and nutrient content make it perfect for root development."},
            {"month": "June", "crop": "Root Vegetables", "action": "In May, plant root vegetables such as carrots or beets. Loamy soil's good drainage and nutrient content make it perfect for root development."},
            {"month": "July", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Plant cucumbers or zucchini in July. These crops thrive in the warm weather and benefit from the balanced texture of loamy soil."},
            {"month": "August", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Plant cucumbers or zucchini in July. These crops thrive in the warm weather and benefit from the balanced texture of loamy soil."},
            {"month": "September", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In September, plant spinach or lettuce. These leafy greens can handle the cooler fall temperatures and grow well in loamy soil."},
            {"month": "October", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In September, plant spinach or lettuce. These leafy greens can handle the cooler fall temperatures and grow well in loamy soil."},
            {"month": "November", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These crops help improve soil structure and add organic matter to loamy soil."},
            {"month": "December", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These crops help improve soil structure and add organic matter to loamy soil."}
        ],
        "summarybycroptype": [
            {"month": "January", "summary": "Legumes (Peas)"},
            {"month": "February", "summary": "Legumes (Peas)"},
            {"month": "March", "summary": "Brassicas (Cabbage/Cauliflower)"},
            {"month": "April", "summary": "Brassicas (Cabbage/Cauliflower)"},
            {"month": "May", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "June", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "July", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "August", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "September", "summary": "Leafy Greens (Spinach/Lettuce)"},
            {"month": "October", "summary": "Leafy Greens (Spinach/Lettuce)"},
            {"month": "November", "summary": "Green Manure (Clover/Vetch)"},
            {"month": "December", "summary": "Green Manure (Clover/Vetch)"}
        ],
        "additionaltips": "Legumes (Peas): January-February. Brassicas (Cabbage/Cauliflower): March-April. Root Vegetables (Carrots/Beets): May-June. Cucurbits (Cucumbers/Zucchini): July-August. Leafy Greens (Spinach/Lettuce): September-October. Green Manure (Clover/Vetch): November-December."
    },
    {
        "title": "Peaty Soil",
        "image": "https://www.boughton.co.uk/wp-content/uploads/sites/14/2019/07/Peat-Soil.jpg",
        "monthlycycle": [
            {"month": "January", "crop": "Peas (Legumes)", "action": "Peas can be planted in peaty soil during the winter months. They help improve soil fertility by fixing nitrogen. Plant in January and let them grow until February."},
            {"month": "February", "crop": "Peas (Legumes)", "action": "Peas can be planted in peaty soil during the winter months. They help improve soil fertility by fixing nitrogen. Plant in January and let them grow until February."},
            {"month": "March", "crop": "Brassicas", "action": "In early spring, plant brassicas like cabbage or broccoli. Peaty soil's high organic content is ideal for these nutrient-demanding crops."},
            {"month": "April", "crop": "Brassicas", "action": "In early spring, plant brassicas like cabbage or broccoli. Peaty soil's high organic content is ideal for these nutrient-demanding crops."},
            {"month": "May", "crop": "Root Vegetables", "action": "Plant root vegetables such as carrots or beets in May. Peaty soil’s high organic matter supports healthy root development. Harvest by late June."},
            {"month": "June", "crop": "Root Vegetables", "action": "Plant root vegetables such as carrots or beets in May. Peaty soil’s high organic matter supports healthy root development. Harvest by late June."},
            {"month": "July", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Plant cucumbers or zucchini in July. These summer crops thrive in the warm weather and benefit from peaty soil’s moisture retention."},
            {"month": "August", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Plant cucumbers or zucchini in July. These summer crops thrive in the warm weather and benefit from peaty soil’s moisture retention."},
            {"month": "September", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In early fall, plant spinach or lettuce. These leafy greens grow well in peaty soil and benefit from the cooler temperatures."},
            {"month": "October", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In early fall, plant spinach or lettuce. These leafy greens grow well in peaty soil and benefit from the cooler temperatures."},
            {"month": "November", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These crops improve soil fertility and structure, adding organic matter to peaty soil."},
            {"month": "December", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These crops improve soil fertility and structure, adding organic matter to peaty soil."}
        ],
        "summarybycroptype": [
            {"month": "January", "summary": "Legumes (Peas)"},
            {"month": "February", "summary": "Legumes (Peas)"},
            {"month": "March", "summary": "Brassicas (Cabbage/Broccoli)"},
            {"month": "April", "summary": "Brassicas (Cabbage/Broccoli)"},
            {"month": "May", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "June", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "July", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "August", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "September", "summary": "Leafy Greens (Spinach/Lettuce)"},
            {"month": "October", "summary": "Leafy Greens (Spinach/Lettuce)"},
            {"month": "November", "summary": "Green Manure (Clover/Vetch)"},
            {"month": "December", "summary": "Green Manure (Clover/Vetch)"}
        ],
        "additionaltips": "Legumes (Peas): January-February. Brassicas (Cabbage/Broccoli): March-April. Root Vegetables (Carrots/Beets): May-June. Cucurbits (Cucumbers/Zucchini): July-August. Leafy Greens (Spinach/Lettuce): September-October. Green Manure (Clover/Vetch): November-December."
    },
    {
        "title": "Chalky Soil",
        "image": "https://www.boughton.co.uk/wp-content/uploads/sites/14/2019/07/Chalk-Soil.jpg",
        "monthlycycle": [
            {"month": "January", "crop": "Peas (Legumes)", "action": "Peas can be grown in chalky soil during winter. They improve soil fertility by fixing nitrogen. Plant in January and let them grow until February."},
            {"month": "February", "crop": "Peas (Legumes)", "action": "Peas can be grown in chalky soil during winter. They improve soil fertility by fixing nitrogen. Plant in January and let them grow until February."},
            {"month": "March", "crop": "Brassicas", "action": "Plant brassicas like cabbage or cauliflower in early spring. They tolerate chalky soil's alkaline nature and grow well in the cool weather."},
            {"month": "April", "crop": "Brassicas", "action": "Plant brassicas like cabbage or cauliflower in early spring. They tolerate chalky soil's alkaline nature and grow well in the cool weather."},
            {"month": "May", "crop": "Root Vegetables", "action": "In May, plant root vegetables such as carrots or beets. Chalky soil’s drainage and nutrient content are suitable for these crops. Harvest by late June."},
            {"month": "June", "crop": "Root Vegetables", "action": "In May, plant root vegetables such as carrots or beets. Chalky soil’s drainage and nutrient content are suitable for these crops. Harvest by late June."},
            {"month": "July", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Plant cucumbers or zucchini in July. These summer crops thrive in the warm weather and adapt well to the well-drained nature of chalky soil."},
            {"month": "August", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "Plant cucumbers or zucchini in July. These summer crops thrive in the warm weather and adapt well to the well-drained nature of chalky soil."},
            {"month": "September", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In early fall, plant spinach or lettuce. These leafy greens can tolerate the alkaline conditions of chalky soil and grow well in cooler temperatures."},
            {"month": "October", "crop": "Spinach or Lettuce (Leafy Greens)", "action": "In early fall, plant spinach or lettuce. These leafy greens can tolerate the alkaline conditions of chalky soil and grow well in cooler temperatures."},
            {"month": "November", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These crops help improve soil fertility and structure in chalky soil."},
            {"month": "December", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These crops help improve soil fertility and structure in chalky soil."}
        ],
        "summarybycroptype": [
            {"month": "January", "summary": "Legumes (Peas)"},
            {"month": "February", "summary": "Legumes (Peas)"},
            {"month": "March", "summary": "Brassicas (Cabbage/Cauliflower)"},
            {"month": "April", "summary": "Brassicas (Cabbage/Cauliflower)"},
            {"month": "May", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "June", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "July", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "August", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "September", "summary": "Leafy Greens (Spinach/Lettuce)"},
            {"month": "October", "summary": "Leafy Greens (Spinach/Lettuce)"},
            {"month": "November", "summary": "Green Manure (Clover/Vetch)"},
            {"month": "December", "summary": "Green Manure (Clover/Vetch)"}
        ],
        "additionaltips": "Legumes (Peas): January-February. Brassicas (Cabbage/Cauliflower): March-April. Root Vegetables (Carrots/Beets): May-June. Cucurbits (Cucumbers/Zucchini): July-August. Leafy Greens (Spinach/Lettuce): September-October. Green Manure (Clover/Vetch): November-December."
    },
    {
        "title": "Saline Soil",
        "image": "https://palayeshcood.com/wp-content/uploads/2023/09/Saline-soil-for-agriculture.jpg",
        "monthlycycle": [
            {"month": "January", "crop": "Barley (Cereals)", "action": "Barley is a good choice for saline soil in winter as it can tolerate higher salinity levels. Plant in January and let it grow until February."},
            {"month": "February", "crop": "Barley (Cereals)", "action": "Barley is a good choice for saline soil in winter as it can tolerate higher salinity levels. Plant in January and let it grow until February."},
            {"month": "March", "crop": "Spinach or Swiss Chard (Leafy Greens)", "action": "In early spring, plant spinach or Swiss chard. Both can tolerate saline conditions and benefit from the cooler weather."},
            {"month": "April", "crop": "Spinach or Swiss Chard (Leafy Greens)", "action": "In early spring, plant spinach or Swiss chard. Both can tolerate saline conditions and benefit from the cooler weather."},
            {"month": "May", "crop": "Tomatoes or Peppers (Fruiting Vegetables)", "action": "In May, plant tomatoes or peppers. They can adapt to slightly saline soil and thrive in the warmer weather."},
            {"month": "June", "crop": "Tomatoes or Peppers (Fruiting Vegetables)", "action": "In May, plant tomatoes or peppers. They can adapt to slightly saline soil and thrive in the warmer weather."},
            {"month": "July", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "In July, plant cucumbers or zucchini. These crops do well in warmer weather and can tolerate saline soil to some extent."},
            {"month": "August", "crop": "Cucumbers or Zucchini (Cucurbits)", "action": "In July, plant cucumbers or zucchini. These crops do well in warmer weather and can tolerate saline soil to some extent."},
            {"month": "September", "crop": "Carrots or Beets (Root Vegetables)", "action": "In early fall, plant carrots or beets. These root vegetables can handle the cooler temperatures and slightly saline conditions."},
            {"month": "October", "crop": "Carrots or Beets (Root Vegetables)", "action": "In early fall, plant carrots or beets. These root vegetables can handle the cooler temperatures and slightly saline conditions."},
            {"month": "November", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These can help improve soil fertility and structure even in saline conditions."},
            {"month": "December", "crop": "Green Manure", "action": "Plant green manure crops like clover or vetch in November. These can help improve soil fertility and structure even in saline conditions."}
        ],
        "summarybycroptype": [
            {"month": "January", "summary": "Cereals (Barley)"},
            {"month": "February", "summary": "Cereals (Barley)"},
            {"month": "March", "summary": "Leafy Greens (Spinach/Swiss Chard)"},
            {"month": "April", "summary": "Leafy Greens (Spinach/Swiss Chard)"},
            {"month": "May", "summary": "Fruiting Vegetables (Tomatoes/Peppers)"},
            {"month": "June", "summary": "Fruiting Vegetables (Tomatoes/Peppers)"},
            {"month": "July", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "August", "summary": "Cucurbits (Cucumbers/Zucchini)"},
            {"month": "September", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "October", "summary": "Root Vegetables (Carrots/Beets)"},
            {"month": "November", "summary": "Green Manure (Clover/Vetch)"},
            {"month": "December", "summary": "Green Manure (Clover/Vetch)"}
        ],
        "additionaltips": "Cereals (Barley): January-February. Leafy Greens (Spinach/Swiss Chard): March-April. Fruiting Vegetables (Tomatoes/Peppers): May-June. Cucurbits (Cucumbers/Zucchini): July-August. Root Vegetables (Carrots/Beets): September-October. Green Manure (Clover/Vetch): November-December."
    }
];

module.exports = { data: samplelistings};
